name: PERNEcommerceApp pipeline

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
    types: [opened, synchronize] 

jobs: 
  deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Check frontend style
        run: npm run lint
        working-directory: frontend

      - name: Check backend style
        run: npm run lint
        working-directory: backend

      # TODO: Add unit and integration tests

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }} \
            -t northshop .
      
      # TODO: Add E2E tests
      
  
  
